### ISSUE TITLE
不能读取数据

### ISSUE THREAD

**Issue by ZYN-guy** [spytensor/pytorch_img_classification_for_competition#2]
loading train dataset
0it [00:00, ?it/s]
loading train dataset
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "main.py", line 322, in <module>
    main()
  File "main.py", line 106, in main
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution
loading train dataset
0it [00:00, ?it/s]
loading train dataset
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "main.py", line 322, in <module>
    main()
  File "main.py", line 106, in main
    num_workers=configs.workers, pin_memory=True,
  File "/home/zhangyanan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 213, in __init__
    sampler = RandomSampler(dataset)
  File "/home/zhangyanan/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

**Comment by spytensor** [comment]
你的数据路径结构是什么样的？默认是：
- dataset/train
-dataset/val
其中train/val下面每个类别单独一个文件夹

**Comment by ZYN-guy** [comment]
感谢您的回复  结构是对的，不过我的照片都在一个文件夹里（train），我没有设置val，也没有区分类别，不多对应的csv文件中将每个照片都对应类：
images_path               lables

images/a.png                 0
images/b.png                 1
请问我怎样才能转换成代码要求格式
















在 2020-05-17 09:52:29，"spytensor" <notifications@github.com> 写道：

你的数据路径结构是什么样的？默认是：

dataset/train
-dataset/val
其中train/val下面每个类别单独一个文件夹
