### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by cats0212** [spytensor/pytorch_img_classification_for_competition#9]
Traceback (most recent call last):
  File "/home/chen/download/pytorch_img_classification_for_competition-master/main.py", line 308, in <module>
    main()
  File "/home/chen/download/pytorch_img_classification_for_competition-master/main.py", line 158, in main
    train_loss, train_acc, train_5 = train(train_loader, model, criterion, optimizer, epoch)
  File "/home/chen/download/pytorch_img_classification_for_competition-master/main.py", line 207, in train
    bar = Bar('Training: ', max=len(train_loader))
  File "/home/chen/download/pythonProject8/lib/python3.7/site-packages/progressbar/widgets.py", line 710, in __init__
    self.marker = create_marker(marker, marker_wrap)
  File "/home/chen/download/pythonProject8/lib/python3.7/site-packages/progressbar/widgets.py", line 90, in create_marker
    'Markers are required to be 1 char'
AssertionError: Markers are required to be 1 char

Process finished with exit code 1

您好请问以上的错误是因为我dataset目录结构有问题吗？可是在您之前的项目，https://github.com/spytensor/pytorch-image-classification，我是可以成功运行得出结果的。十分感谢您百忙中的回复，谢谢

**Comment by cats0212** [comment]
pytorch也是1.4.0版本的

**Comment by cats0212** [comment]
loading train dataset
100%|██████████| 15812/15812 [00:00<00:00, 1458615.62it/s]
100%|██████████| 2774/2774 [00:00<00:00, 1498969.25it/s]
loading train dataset
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'")

Epoch: [1 | 10] LR: 0.002000
Traceback (most recent call last):
  File "/home/chen/download/pytorch_img_classification_for_competition-master/main.py", line 308, in <module>
    main()
  File "/home/chen/download/pytorch_img_classification_for_competition-master/main.py", line 158, in main
    train_loss, train_acc, train_5 = train(train_loader, model, criterion, optimizer, epoch)
  File "/home/chen/download/pytorch_img_classification_for_competition-master/main.py", line 207, in train
    bar = Bar('Training: ', max=len(train_loader))
  File "/home/chen/download/pythonProject8/lib/python3.7/site-packages/progressbar/widgets.py", line 710, in __init__
    self.marker = create_marker(marker, marker_wrap)
  File "/home/chen/download/pythonProject8/lib/python3.7/site-packages/progressbar/widgets.py", line 90, in create_marker
    'Markers are required to be 1 char'
AssertionError: Markers are required to be 1 char

Process finished with exit code 1
